# Interactive Visualizations in Notebooks

In [4]:
pip install scipy

Collecting scipy
  Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting numpy<2.7,>=1.26.4 (from scipy)
  Downloading numpy-2.4.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.5 MB ? eta -:--:--
    --------------------------------------- 0.5/36.5 MB 644.1 kB/s eta 0:00:56
    --------------------------------------- 0.5/36.5 MB 644.1 kB/s eta 0:00:56
    --------------------------------------- 0.8/36.5 MB 657.8 kB/s eta 0:00:55
    --------------------------------------- 0.8/36.5 MB 657.8 kB/s eta 0:00:55
   - -------------------------------------- 1.0/36.5 MB 653.2 kB/s eta 0:00:55
   - -------------------------------------- 1.3/36.5 MB 780.2 kB/s eta 0:00:46
   - -------------------------------------- 1.3/36.5 MB 780.2 kB/s eta 0:00:46
   - -------------------------------------- 1.6/36.5 MB 762.5 kB/s eta 0:00:46
   -- ------------------------------------- 1.8/36.5 MB 756.5 kB/s eta 0:00:46
   -- ------------------------------------- 1.8/36.5 MB 756.5 kB/s eta 0:00:46
   -- ------------------------------------- 2.1/36.5 MB 767.5 kB/s eta 0:00:45
   -- ------------------------------------- 2.4/36.5 MB 771.3 kB/s eta 0:00:45
   -- ------------------------------------- 2.4/36.5 MB 771.3 kB/s eta 0:00:45
   -- ------------------------------------- 2.6/36.5 MB 774.3 kB/s eta 0:00:44
   -- ------------------------------------- 2.6/36.5 MB 774.3 kB/s eta 0:00:44
   --- ------------------------------------ 2.9/36.5 MB 735.7 kB/s eta 0:00:46
   --- ------------------------------------ 2.9/36.5 MB 735.7 kB/s eta 0:00:46
   --- ------------------------------------ 3.1/36.5 MB 759.4 kB/s eta 0:00:44
   --- ------------------------------------ 3.4/36.5 MB 745.6 kB/s eta 0:00:45
   --- ------------------------------------ 3.4/36.5 MB 745.6 kB/s eta 0:00:45
   ---- ----------------------------------- 3.7/36.5 MB 739.2 kB/s eta 0:00:45
   ---- ----------------------------------- 3.7/36.5 MB 739.2 kB/s eta 0:00:45
   ---- ----------------------------------- 3.9/36.5 MB 734.0 kB/s eta 0:00:45
   ---- ----------------------------------- 3.9/36.5 MB 734.0 kB/s eta 0:00:45
   ---- ----------------------------------- 4.2/36.5 MB 731.6 kB/s eta 0:00:45
   ---- ----------------------------------- 4.2/36.5 MB 731.6 kB/s eta 0:00:45
   ---- ----------------------------------- 4.5/36.5 MB 731.4 kB/s eta 0:00:44
   ----- ---------------------------------- 4.7/36.5 MB 729.4 kB/s eta 0:00:44
   ----- ---------------------------------- 4.7/36.5 MB 729.4 kB/s eta 0:00:44
   ----- ---------------------------------- 5.0/36.5 MB 725.9 kB/s eta 0:00:44
   ----- ---------------------------------- 5.0/36.5 MB 725.9 kB/s eta 0:00:44
   ----- ---------------------------------- 5.2/36.5 MB 722.8 kB/s eta 0:00:44
   ----- ---------------------------------- 5.2/36.5 MB 722.8 kB/s eta 0:00:44
   ------ --------------------------------- 5.5/36.5 MB 720.0 kB/s eta 0:00:44
   ------ --------------------------------- 5.5/36.5 MB 720.0 kB/s eta 0:00:44
   ------ --------------------------------- 5.8/36.5 MB 717.5 kB/s eta 0:00:43
   ------ --------------------------------- 6.0/36.5 MB 715.3 kB/s eta 0:00:43
   ------ --------------------------------- 6.0/36.5 MB 715.3 kB/s eta 0:00:43
   ------ --------------------------------- 6.3/36.5 MB 714.5 kB/s eta 0:00:43
   ------ --------------------------------- 6.3/36.5 MB 714.5 kB/s eta 0:00:43
   ------- -------------------------------- 6.6/36.5 MB 715.2 kB/s eta 0:00:42
   ------- -------------------------------- 6.6/36.5 MB 715.2 kB/s eta 0:00:42
   ------- -------------------------------- 6.8/36.5 MB 715.7 kB/s eta 0:00:42
   ------- -------------------------------- 7.1/36.5 MB 716.2 kB/s eta 0:00:42
   ------- -------------------------------- 7.1/36.5 MB 716.2 kB/s eta 0:00:42
   -------- ------------------------------- 7.3/36.5 MB 716.7 kB/s eta 0:00:41
   -------- ------------------------------- 7.3/36.5 MB 716.7 kB/s eta 0:00:41
   -------- ------------------------------- 7.6/36.5 MB 719.3 kB/s eta 0:00:41
   -------- ------------------------------- 7.9/36.5 MB 724.0 kB/s eta 0:00:40
   -------- ------------------------------- 7.9/36.5 MB 724.0 kB/s eta 0:00:40
   -------- ------------------------------- 8.1/36.5 MB 727.3 kB/s eta 0:00:40
   --------- ------------------------------ 8.4/36.5 MB 729.4 kB/s eta 0:00:39
   --------- ------------------------------ 8.4/36.5 MB 729.4 kB/s eta 0:00:39
   --------- ------------------------------ 8.7/36.5 MB 728.4 kB/s eta 0:00:39
   --------- ------------------------------ 8.7/36.5 MB 728.4 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 726.5 kB/s eta 0:00:39
   --------- ------------------------------ 8.9/36.5 MB 726.5 kB/s eta 0:00:39
   ---------- ----------------------------- 9.2/36.5 MB 726.6 kB/s eta 0:00:38
   ---------- ----------------------------- 9.2/36.5 MB 726.6 kB/s eta 0:00:38
   ---------- ----------------------------- 9.4/36.5 MB 728.5 kB/s eta 0:00:38
   ---------- ----------------------------- 9.7/36.5 MB 731.2 kB/s eta 0:00:37
   ---------- ----------------------------- 9.7/36.5 MB 731.2 kB/s eta 0:00:37
   ---------- ----------------------------- 10.0/36.5 MB 734.6 kB/s eta 0:00:37
   ---------- ----------------------------- 10.0/36.5 MB 734.6 kB/s eta 0:00:37
   ----------- ---------------------------- 10.2/36.5 MB 725.3 kB/s eta 0:00:37
   ----------- ---------------------------- 10.5/36.5 MB 736.0 kB/s eta 0:00:36
   ----------- ---------------------------- 10.5/36.5 MB 736.0 kB/s eta 0:00:36
   ----------- ---------------------------- 10.7/36.5 MB 732.6 kB/s eta 0:00:36
   ----------- ---------------------------- 10.7/36.5 MB 732.6 kB/s eta 0:00:36
   ------------ --------------------------- 11.0/36.5 MB 731.0 kB/s eta 0:00:35
   ------------ --------------------------- 11.0/36.5 MB 731.0 kB/s eta 0:00:35
   ------------ --------------------------- 11.3/36.5 MB 730.9 kB/s eta 0:00:35
   ------------ --------------------------- 11.5/36.5 MB 730.9 kB/s eta 0:00:35
   ------------ --------------------------- 11.5/36.5 MB 730.9 kB/s eta 0:00:35
   ------------ --------------------------- 11.8/36.5 MB 730.9 kB/s eta 0:00:34
   ------------ --------------------------- 11.8/36.5 MB 730.9 kB/s eta 0:00:34
   ------------- -------------------------- 12.1/36.5 MB 730.8 kB/s eta 0:00:34
   ------------- -------------------------- 12.1/36.5 MB 730.8 kB/s eta 0:00:34
   ------------- -------------------------- 12.3/36.5 MB 731.5 kB/s eta 0:00:34
   ------------- -------------------------- 12.6/36.5 MB 732.1 kB/s eta 0:00:33
   ------------- -------------------------- 12.6/36.5 MB 732.1 kB/s eta 0:00:33
   -------------- ------------------------- 12.8/36.5 MB 732.1 kB/s eta 0:00:33
   -------------- ------------------------- 13.1/36.5 MB 732.7 kB/s eta 0:00:32
   -------------- ------------------------- 13.1/36.5 MB 732.7 kB/s eta 0:00:32
   -------------- ------------------------- 13.4/36.5 MB 733.3 kB/s eta 0:00:32
   -------------- ------------------------- 13.4/36.5 MB 733.3 kB/s eta 0:00:32
   -------------- ------------------------- 13.6/36.5 MB 733.8 kB/s eta 0:00:32
   --------------- ------------------------ 13.9/36.5 MB 734.3 kB/s eta 0:00:31
   --------------- ------------------------ 13.9/36.5 MB 734.3 kB/s eta 0:00:31
   --------------- ------------------------ 14.2/36.5 MB 734.8 kB/s eta 0:00:31
   --------------- ------------------------ 14.2/36.5 MB 734.8 kB/s eta 0:00:31
   --------------- ------------------------ 14.4/36.5 MB 735.4 kB/s eta 0:00:31
   ---------------- ----------------------- 14.7/36.5 MB 735.8 kB/s eta 0:00:30
   ---------------- ----------------------- 14.7/36.5 MB 735.8 kB/s eta 0:00:30
   ---------------- ----------------------- 14.9/36.5 MB 736.9 kB/s eta 0:00:30
   ---------------- ----------------------- 14.9/36.5 MB 736.9 kB/s eta 0:00:30
   ---------------- ----------------------- 15.2/36.5 MB 738.4 kB/s eta 0:00:29
   ---------------- ----------------------- 15.5/36.5 MB 740.0 kB/s eta 0:00:29
   ---------------- ----------------------- 15.5/36.5 MB 740.0 kB/s eta 0:00:29
   ----------------- ---------------------- 15.7/36.5 MB 738.1 kB/s eta 0:00:29
   ----------------- ---------------------- 15.7/36.5 MB 738.1 kB/s eta 0:00:29
   ----------------- ---------------------- 16.0/36.5 MB 739.1 kB/s eta 0:00:28
   ----------------- ---------------------- 16.0/36.5 MB 739.1 kB/s eta 0:00:28
   ----------------- ---------------------- 16.3/36.5 MB 737.9 kB/s eta 0:00:28
   ----------------- ---------------------- 16.3/36.5 MB 737.9 kB/s eta 0:00:28
   ------------------ --------------------- 16.5/36.5 MB 735.1 kB/s eta 0:00:28
   ------------------ --------------------- 16.5/36.5 MB 735.1 kB/s eta 0:00:28
   ------------------ --------------------- 16.8/36.5 MB 735.0 kB/s eta 0:00:27
   ------------------ --------------------- 17.0/36.5 MB 735.9 kB/s eta 0:00:27
   ------------------ --------------------- 17.0/36.5 MB 735.9 kB/s eta 0:00:27
   ------------------ --------------------- 17.3/36.5 MB 737.3 kB/s eta 0:00:27
   ------------------- -------------------- 17.6/36.5 MB 738.2 kB/s eta 0:00:26
   ------------------- -------------------- 17.6/36.5 MB 738.2 kB/s eta 0:00:26
   ------------------- -------------------- 17.8/36.5 MB 736.1 kB/s eta 0:00:26
   ------------------- -------------------- 17.8/36.5 MB 736.1 kB/s eta 0:00:26
   ------------------- -------------------- 18.1/36.5 MB 735.5 kB/s eta 0:00:26
   ------------------- -------------------- 18.1/36.5 MB 735.5 kB/s eta 0:00:26
   -------------------- ------------------- 18.4/36.5 MB 734.5 kB/s eta 0:00:25
   -------------------- ------------------- 18.4/36.5 MB 734.5 kB/s eta 0:00:25
   -------------------- ------------------- 18.6/36.5 MB 733.5 kB/s eta 0:00:25
   -------------------- ------------------- 18.6/36.5 MB 733.5 kB/s eta 0:00:25
   -------------------- ------------------- 18.9/36.5 MB 733.0 kB/s eta 0:00:25
   -------------------- ------------------- 18.9/36.5 MB 733.0 kB/s eta 0:00:25
   -------------------- ------------------- 19.1/36.5 MB 733.4 kB/s eta 0:00:24
   --------------------- ------------------ 19.4/36.5 MB 733.4 kB/s eta 0:00:24
   --------------------- ------------------ 19.4/36.5 MB 733.4 kB/s eta 0:00:24
   --------------------- ------------------ 19.7/36.5 MB 732.9 kB/s eta 0:00:24
   --------------------- ------------------ 19.7/36.5 MB 732.9 kB/s eta 0:00:24
   --------------------- ------------------ 19.9/36.5 MB 733.3 kB/s eta 0:00:23
   --------------------- ------------------ 19.9/36.5 MB 733.3 kB/s eta 0:00:23
   ---------------------- ----------------- 20.2/36.5 MB 733.6 kB/s eta 0:00:23
   ---------------------- ----------------- 20.4/36.5 MB 733.6 kB/s eta 0:00:22
   ---------------------- ----------------- 20.4/36.5 MB 733.6 kB/s eta 0:00:22
   ---------------------- ----------------- 20.7/36.5 MB 733.5 kB/s eta 0:00:22
   ---------------------- ----------------- 20.7/36.5 MB 733.5 kB/s eta 0:00:22
   ---------------------- ----------------- 21.0/36.5 MB 733.1 kB/s eta 0:00:22
   ---------------------- ----------------- 21.0/36.5 MB 733.1 kB/s eta 0:00:22
   ----------------------- ---------------- 21.2/36.5 MB 733.4 kB/s eta 0:00:21
   ----------------------- ---------------- 21.5/36.5 MB 733.8 kB/s eta 0:00:21
   ----------------------- ---------------- 21.5/36.5 MB 733.8 kB/s eta 0:00:21
   ----------------------- ---------------- 21.8/36.5 MB 733.3 kB/s eta 0:00:21
   ----------------------- ---------------- 21.8/36.5 MB 733.3 kB/s eta 0:00:21
   ------------------------ --------------- 22.0/36.5 MB 734.0 kB/s eta 0:00:20
   ------------------------ --------------- 22.0/36.5 MB 734.0 kB/s eta 0:00:20
   ------------------------ --------------- 22.3/36.5 MB 734.4 kB/s eta 0:00:20
   ------------------------ --------------- 22.5/36.5 MB 736.7 kB/s eta 0:00:20
   ------------------------ --------------- 22.5/36.5 MB 736.7 kB/s eta 0:00:20
   ------------------------ --------------- 22.8/36.5 MB 738.2 kB/s eta 0:00:19
   ------------------------- -------------- 23.1/36.5 MB 741.0 kB/s eta 0:00:19
   ------------------------- -------------- 23.1/36.5 MB 741.0 kB/s eta 0:00:19
   ------------------------- -------------- 23.3/36.5 MB 733.3 kB/s eta 0:00:19
   ------------------------- -------------- 23.3/36.5 MB 733.3 kB/s eta 0:00:19
   ------------------------- -------------- 23.6/36.5 MB 734.8 kB/s eta 0:00:18
   ------------------------- -------------- 23.6/36.5 MB 734.8 kB/s eta 0:00:18
   -------------------------- ------------- 23.9/36.5 MB 734.4 kB/s eta 0:00:18
   -------------------------- ------------- 24.1/36.5 MB 732.9 kB/s eta 0:00:17
   -------------------------- ------------- 24.1/36.5 MB 732.9 kB/s eta 0:00:17
   -------------------------- ------------- 24.4/36.5 MB 732.9 kB/s eta 0:00:17
   -------------------------- ------------- 24.4/36.5 MB 732.9 kB/s eta 0:00:17
   -------------------------- ------------- 24.6/36.5 MB 737.2 kB/s eta 0:00:17
   --------------------------- ------------ 24.9/36.5 MB 738.6 kB/s eta 0:00:16
   --------------------------- ------------ 24.9/36.5 MB 738.6 kB/s eta 0:00:16
   --------------------------- ------------ 25.2/36.5 MB 735.9 kB/s eta 0:00:16
   --------------------------- ------------ 25.2/36.5 MB 735.9 kB/s eta 0:00:16
   --------------------------- ------------ 25.4/36.5 MB 737.1 kB/s eta 0:00:16
   ---------------------------- ----------- 25.7/36.5 MB 739.4 kB/s eta 0:00:15
   ---------------------------- ----------- 25.7/36.5 MB 739.4 kB/s eta 0:00:15
   ---------------------------- ----------- 26.0/36.5 MB 741.3 kB/s eta 0:00:15
   ---------------------------- ----------- 26.0/36.5 MB 741.3 kB/s eta 0:00:15
   ---------------------------- ----------- 26.2/36.5 MB 740.9 kB/s eta 0:00:14
   ---------------------------- ----------- 26.2/36.5 MB 740.9 kB/s eta 0:00:14
   ---------------------------- ----------- 26.5/36.5 MB 740.2 kB/s eta 0:00:14
   ----------------------------- ---------- 26.7/36.5 MB 740.9 kB/s eta 0:00:14
   ----------------------------- ---------- 26.7/36.5 MB 740.9 kB/s eta 0:00:14
   ----------------------------- ---------- 27.0/36.5 MB 741.7 kB/s eta 0:00:13
   ----------------------------- ---------- 27.0/36.5 MB 741.7 kB/s eta 0:00:13
   ----------------------------- ---------- 27.3/36.5 MB 742.7 kB/s eta 0:00:13
   ------------------------------ --------- 27.5/36.5 MB 744.3 kB/s eta 0:00:13
   ------------------------------ --------- 27.5/36.5 MB 744.3 kB/s eta 0:00:13
   ------------------------------ --------- 27.8/36.5 MB 745.8 kB/s eta 0:00:12
   ------------------------------ --------- 27.8/36.5 MB 745.8 kB/s eta 0:00:12
   ------------------------------ --------- 28.0/36.5 MB 743.9 kB/s eta 0:00:12
   ------------------------------ --------- 28.3/36.5 MB 747.0 kB/s eta 0:00:12
   ------------------------------ --------- 28.3/36.5 MB 747.0 kB/s eta 0:00:12
   ------------------------------- -------- 28.6/36.5 MB 746.2 kB/s eta 0:00:11
   ------------------------------- -------- 28.6/36.5 MB 746.2 kB/s eta 0:00:11
   ------------------------------- -------- 28.8/36.5 MB 745.4 kB/s eta 0:00:11
   ------------------------------- -------- 28.8/36.5 MB 745.4 kB/s eta 0:00:11
   ------------------------------- -------- 29.1/36.5 MB 745.1 kB/s eta 0:00:11
   ------------------------------- -------- 29.1/36.5 MB 745.1 kB/s eta 0:00:11
   -------------------------------- ------- 29.4/36.5 MB 745.1 kB/s eta 0:00:10
   -------------------------------- ------- 29.4/36.5 MB 745.1 kB/s eta 0:00:10
   -------------------------------- ------- 29.6/36.5 MB 745.0 kB/s eta 0:00:10
   -------------------------------- ------- 29.6/36.5 MB 745.0 kB/s eta 0:00:10
   -------------------------------- ------- 29.9/36.5 MB 744.3 kB/s eta 0:00:09
   -------------------------------- ------- 30.1/36.5 MB 741.3 kB/s eta 0:00:09
   -------------------------------- ------- 30.1/36.5 MB 741.3 kB/s eta 0:00:09
   --------------------------------- ------ 30.4/36.5 MB 740.6 kB/s eta 0:00:09
   --------------------------------- ------ 30.4/36.5 MB 740.6 kB/s eta 0:00:09
   --------------------------------- ------ 30.7/36.5 MB 740.9 kB/s eta 0:00:08
   --------------------------------- ------ 30.7/36.5 MB 740.9 kB/s eta 0:00:08
   --------------------------------- ------ 30.9/36.5 MB 742.1 kB/s eta 0:00:08
   ---------------------------------- ----- 31.2/36.5 MB 742.1 kB/s eta 0:00:08
   ---------------------------------- ----- 31.2/36.5 MB 742.1 kB/s eta 0:00:08
   ---------------------------------- ----- 31.5/36.5 MB 740.9 kB/s eta 0:00:07
   ---------------------------------- ----- 31.5/36.5 MB 740.9 kB/s eta 0:00:07
   ---------------------------------- ----- 31.7/36.5 MB 740.2 kB/s eta 0:00:07
   ---------------------------------- ----- 31.7/36.5 MB 740.2 kB/s eta 0:00:07
   ----------------------------------- ---- 32.0/36.5 MB 737.9 kB/s eta 0:00:07
   ----------------------------------- ---- 32.0/36.5 MB 737.9 kB/s eta 0:00:07
   ----------------------------------- ---- 32.2/36.5 MB 742.9 kB/s eta 0:00:06
   ----------------------------------- ---- 32.5/36.5 MB 743.5 kB/s eta 0:00:06
   ----------------------------------- ---- 32.5/36.5 MB 743.5 kB/s eta 0:00:06
   ----------------------------------- ---- 32.8/36.5 MB 740.2 kB/s eta 0:00:06
   ------------------------------------ --- 33.0/36.5 MB 742.5 kB/s eta 0:00:05
   ------------------------------------ --- 33.0/36.5 MB 742.5 kB/s eta 0:00:05
   ------------------------------------ --- 33.3/36.5 MB 743.9 kB/s eta 0:00:05
   ------------------------------------ --- 33.3/36.5 MB 743.9 kB/s eta 0:00:05
   ------------------------------------ --- 33.3/36.5 MB 743.9 kB/s eta 0:00:05
   ------------------------------------ --- 33.6/36.5 MB 739.8 kB/s eta 0:00:05
   ------------------------------------- -- 33.8/36.5 MB 743.1 kB/s eta 0:00:04
   ------------------------------------- -- 33.8/36.5 MB 743.1 kB/s eta 0:00:04
   ------------------------------------- -- 34.1/36.5 MB 742.1 kB/s eta 0:00:04
   ------------------------------------- -- 34.3/36.5 MB 742.1 kB/s eta 0:00:03
   ------------------------------------- -- 34.3/36.5 MB 742.1 kB/s eta 0:00:03
   ------------------------------------- -- 34.6/36.5 MB 742.1 kB/s eta 0:00:03
   -------------------------------------- - 34.9/36.5 MB 743.5 kB/s eta 0:00:03
   -------------------------------------- - 34.9/36.5 MB 743.5 kB/s eta 0:00:03
   -------------------------------------- - 35.1/36.5 MB 744.7 kB/s eta 0:00:02
   -------------------------------------- - 35.1/36.5 MB 744.7 kB/s eta 0:00:02
   -------------------------------------- - 35.4/36.5 MB 740.9 kB/s eta 0:00:02
   ---------------------------------------  35.7/36.5 MB 744.3 kB/s eta 0:00:02
   ---------------------------------------  35.7/36.5 MB 744.3 kB/s eta 0:00:02
   ---------------------------------------  35.9/36.5 MB 742.7 kB/s eta 0:00:01
   ---------------------------------------  35.9/36.5 MB 742.7 kB/s eta 0:00:01
   ---------------------------------------  36.2/36.5 MB 741.0 kB/s eta 0:00:01
   ---------------------------------------  36.2/36.5 MB 741.0 kB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 740.5 kB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 740.5 kB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 736.6 kB/s  0:00:49
Downloading numpy-2.4.3-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\Users\\HP\\Desktop\\@data_science_projects_portfolio\\alx_python_track\\.venv\\Lib\\site-packages\\scipy\\optimize\\_shgo.py'
Check the permissions.

In [5]:
pip install ipywidgets

Collecting ipywidgets
  Using cached ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: comm>=0.1.3 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipywidgets) (9.11.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipywidgets) (5.14.3)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets)
  Using cached widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets)
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: executing>=1.2.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
   ---------------------------------------- 0.0/914.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/914.9 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/914.9 kB ? eta -:--:--
   ----------- ---------------------------- 262.1/914.9 kB ? eta -:--:--
   ---------------------- ----------------- 524.3/914.9 kB 1.1 MB/s eta 0:00:01
   -------------------------------- ----- 786.4/914.9 kB 907.1 kB/s eta 0:00:01
   ---------------------------------------- 914.9/914.9 kB 870.4 kB/s  0:00:01
Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 730.2 kB/s eta 0:00:03
   --------- ------------------------------ 0.5/2.2 MB 730.2 kB/s eta 0:00:03
   -------------- ------------------------- 0.8/2.2 MB 745.8 kB/s eta 0:00:02
   -------------- ------------------------- 0.8/2.2 MB 745.8 kB/s eta 0:00:02
   ------------------- -------------------- 1.0/2.2 MB 740.5 kB/s eta 0:00:02
   ----------------------- ---------------- 1.3/2.2 MB 754.4 kB/s eta 0:00:02
   ----------------------- ---------------- 1.3/2.2 MB 754.4 kB/s eta 0:00:02
   ---------------------------- ----------- 1.6/2.2 MB 769.7 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 786.4 kB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.2 MB 786.4 kB/s eta 0:00:01
   -------------------------------------- - 2.1/2.2 MB 767.8 kB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 764.3 kB/s  0:00:02
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets

   ------------- -------------------------- 1/3 [jupyterlab_widgets]
   ------------- -------------------------- 1/3 [jupyterlab_widgets]

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\Users\\HP\\Desktop\\@data_science_projects_portfolio\\alx_python_track\\.venv\\share\\jupyter\\labextensions\\@jupyter-widgets\\jupyterlab-manager\\static\\vendors-node_modules_d3-color_src_color_js-node_modules_d3-format_src_defaultLocale_js-node_m-09b215.2643c43f22ad111f4f82.js'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths

In [6]:
pip install chart-studio

Collecting chart-studio
  Using cached chart_studio-1.1.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: plotly in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from chart-studio) (6.6.0)
Collecting requests (from chart-studio)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting retrying>=1.3.3 (from chart-studio)
  Using cached retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: six in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from chart-studio) (1.17.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from plotly->chart-studio) (2.18.0)
Requirement already satisfied: packaging in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from plotly->chart-studio) (26.0)
Collecting charset_normalizer<4,>=2 (from requests->chart-studio)
  Downloading charset_normalizer-3.4.6-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests->chart-studio)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests->chart-studio)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests->chart-studio)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Using cached chart_studio-1.1.0-py3-none-any.whl (64 kB)
Using cached retrying-1.4.2-py3-none-any.whl (10 kB)
Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.6-cp312-cp312-win_amd64.whl (154 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Installing collected packages: urllib3, retrying, idna, charset_normalizer, certifi, requests, chart-studio

   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ---------------------------------------- 0/7 [urllib3]
   ----------- ---------------------------- 2/7 [idna]
   ----------- ---------------------------- 2/7 [idna]
   ----------- ---------------------------- 2/7 [idna]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ----------------- ---------------------- 3/7 [charset_normalizer]
   ---------------------------- ----------- 5/7 [requests]
   ---------------------------- ----------- 5/7 [requests]
   ---------------------------- ----------- 5/7 [requests]
   ---------------------------------- ----- 6/7 [chart-studio]
   ---------------------------------- ----- 6/7 [chart-studio]
   ---------------------------------- ----- 6/7 [chart-studio]
   ---------------------------------- ----- 6/7 [chart-studio]
   ---------------------------------- ----- 6/7 [chart-studio]
   ---------------------------------------- 7/7 [chart-studio]

Successfully installed certifi-2026.2.25 charset_normalizer-3.4.6 chart-studio-1.1.0 idna-3.11 requests-2.32.5 retrying-1.4.2 urllib3-2.6.3
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install pyarrow

Collecting pyarrow
  Using cached pyarrow-23.0.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl (27.6 MB)
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/27.6 MB ? eta -:--:--
    --------------------------------------- 0.5/27.6 MB 882.6 kB/s eta 0:00:31
    --------------------------------------- 0.5/27.6 MB 882.6 kB/s eta 0:00:31
   - -------------------------------------- 0.8/27.6 MB 860.9 kB/s eta 0:00:32
   - -------------------------------------- 0.8/27.6 MB 860.9 kB/s eta 0:00:32
   - -------------------------------------- 1.0/27.6 MB 774.0 kB/s eta 0:00:35
   - -------------------------------------- 1.3/27.6 MB 762.6 kB/s eta 0:00:35
   - -------------------------------------- 1.3/27.6 MB 762.6 kB/s eta 0:00:35
   -- ------------------------------------- 1.6/27.6 MB 742.2 kB/s eta 0:00:36
   -- ------------------------------------- 1.6/27.6 MB 742.2 kB/s eta 0:00:36
   -- ------------------------------------- 1.8/27.6 MB 745.8 kB/s eta 0:00:35
   -- ------------------------------------- 1.8/27.6 MB 745.8 kB/s eta 0:00:35
   --- ------------------------------------ 2.1/27.6 MB 752.7 kB/s eta 0:00:34
   --- ------------------------------------ 2.4/27.6 MB 762.6 kB/s eta 0:00:34
   --- ------------------------------------ 2.4/27.6 MB 762.6 kB/s eta 0:00:34
   --- ------------------------------------ 2.6/27.6 MB 774.3 kB/s eta 0:00:33
   ---- ----------------------------------- 2.9/27.6 MB 766.1 kB/s eta 0:00:33
   ---- ----------------------------------- 2.9/27.6 MB 766.1 kB/s eta 0:00:33
   ---- ----------------------------------- 3.1/27.6 MB 762.7 kB/s eta 0:00:33
   ---- ----------------------------------- 3.1/27.6 MB 762.7 kB/s eta 0:00:33
   ---- ----------------------------------- 3.4/27.6 MB 765.6 kB/s eta 0:00:32
   ----- ---------------------------------- 3.7/27.6 MB 770.7 kB/s eta 0:00:32
   ----- ---------------------------------- 3.7/27.6 MB 770.7 kB/s eta 0:00:32
   ----- ---------------------------------- 3.9/27.6 MB 772.6 kB/s eta 0:00:31
   ----- ---------------------------------- 3.9/27.6 MB 772.6 kB/s eta 0:00:31
   ------ --------------------------------- 4.2/27.6 MB 767.2 kB/s eta 0:00:31
   ------ --------------------------------- 4.2/27.6 MB 767.2 kB/s eta 0:00:31
   ------ --------------------------------- 4.5/27.6 MB 762.6 kB/s eta 0:00:31
   ------ --------------------------------- 4.5/27.6 MB 762.6 kB/s eta 0:00:31
   ------ --------------------------------- 4.7/27.6 MB 746.6 kB/s eta 0:00:31
   ------ --------------------------------- 4.7/27.6 MB 746.6 kB/s eta 0:00:31
   ------ --------------------------------- 4.7/27.6 MB 746.6 kB/s eta 0:00:31
   ------- -------------------------------- 5.0/27.6 MB 710.5 kB/s eta 0:00:32
   ------- -------------------------------- 5.0/27.6 MB 710.5 kB/s eta 0:00:32
   ------- -------------------------------- 5.0/27.6 MB 710.5 kB/s eta 0:00:32
   ------- -------------------------------- 5.0/27.6 MB 710.5 kB/s eta 0:00:32
   ------- -------------------------------- 5.0/27.6 MB 710.5 kB/s eta 0:00:32
   ------- -------------------------------- 5.0/27.6 MB 710.5 kB/s eta 0:00:32
   ------- -------------------------------- 5.0/27.6 MB 710.5 kB/s eta 0:00:32
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.2/27.6 MB 620.2 kB/s eta 0:00:37
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   ------- -------------------------------- 5.5/27.6 MB 503.1 kB/s eta 0:00:44
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 5.8/27.6 MB 414.0 kB/s eta 0:00:53
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   -------- ------------------------------- 6.0/27.6 MB 353.5 kB/s eta 0:01:02
   --------- ------------------------------ 6.3/27.6 MB 303.1 kB/s eta 0:01:11
   --------- ------------------------------ 6.3/27.6 MB 303.1 kB/s eta 0:01:11
   --------- ------------------------------ 6.3/27.6 MB 303.1 kB/s eta 0:01:11
   --------- ------------------------------ 6.3/27.6 MB 303.1 kB/s eta 0:01:11
   --------- ------------------------------ 6.3/27.6 MB 303.1 kB/s eta 0:01:11
   --------- ------------------------------ 6.3/27.6 MB 303.1 kB/s eta 0:01:11
   --------- ------------------------------ 6.6/27.6 MB 298.0 kB/s eta 0:01:11
   --------- ------------------------------ 6.6/27.6 MB 298.0 kB/s eta 0:01:11
   --------- ------------------------------ 6.6/27.6 MB 298.0 kB/s eta 0:01:11
   --------- ------------------------------ 6.8/27.6 MB 300.0 kB/s eta 0:01:10
   --------- ------------------------------ 6.8/27.6 MB 300.0 kB/s eta 0:01:10
   --------- ------------------------------ 6.8/27.6 MB 300.0 kB/s eta 0:01:10
   ---------- ----------------------------- 7.1/27.6 MB 303.8 kB/s eta 0:01:08
   ---------- ----------------------------- 7.1/27.6 MB 303.8 kB/s eta 0:01:08
   ---------- ----------------------------- 7.1/27.6 MB 303.8 kB/s eta 0:01:08
   ---------- ----------------------------- 7.3/27.6 MB 308.4 kB/s eta 0:01:06
   ---------- ----------------------------- 7.3/27.6 MB 308.4 kB/s eta 0:01:06
   ----------- ---------------------------- 7.6/27.6 MB 313.4 kB/s eta 0:01:04
   ----------- ---------------------------- 7.6/27.6 MB 313.4 kB/s eta 0:01:04
   ----------- ---------------------------- 7.9/27.6 MB 318.8 kB/s eta 0:01:02
   ----------- ---------------------------- 7.9/27.6 MB 318.8 kB/s eta 0:01:02
   ----------- ---------------------------- 8.1/27.6 MB 324.7 kB/s eta 0:01:01
   ----------- ---------------------------- 8.1/27.6 MB 324.7 kB/s eta 0:01:01
   ------------ --------------------------- 8.4/27.6 MB 330.6 kB/s eta 0:00:59
   ------------ --------------------------- 8.4/27.6 MB 330.6 kB/s eta 0:00:59
   ------------ --------------------------- 8.7/27.6 MB 336.4 kB/s eta 0:00:57
   ------------ --------------------------- 8.9/27.6 MB 342.4 kB/s eta 0:00:55
   ------------ --------------------------- 8.9/27.6 MB 342.4 kB/s eta 0:00:55
   ------------- -------------------------- 9.2/27.6 MB 349.1 kB/s eta 0:00:53
   ------------- -------------------------- 9.4/27.6 MB 354.8 kB/s eta 0:00:52
   ------------- -------------------------- 9.4/27.6 MB 354.8 kB/s eta 0:00:52
   -------------- ------------------------- 9.7/27.6 MB 359.9 kB/s eta 0:00:50
   -------------- ------------------------- 9.7/27.6 MB 359.9 kB/s eta 0:00:50
   -------------- ------------------------- 10.0/27.6 MB 364.9 kB/s eta 0:00:49
   -------------- ------------------------- 10.0/27.6 MB 364.9 kB/s eta 0:00:49
   -------------- ------------------------- 10.2/27.6 MB 368.7 kB/s eta 0:00:48
   -------------- ------------------------- 10.2/27.6 MB 368.7 kB/s eta 0:00:48
   --------------- ------------------------ 10.5/27.6 MB 372.6 kB/s eta 0:00:46
   --------------- ------------------------ 10.5/27.6 MB 372.6 kB/s eta 0:00:46
   --------------- ------------------------ 10.5/27.6 MB 372.6 kB/s eta 0:00:46
   --------------- ------------------------ 10.7/27.6 MB 374.9 kB/s eta 0:00:46
   --------------- ------------------------ 10.7/27.6 MB 374.9 kB/s eta 0:00:46
   --------------- ------------------------ 11.0/27.6 MB 379.0 kB/s eta 0:00:44
   --------------- ------------------------ 11.0/27.6 MB 379.0 kB/s eta 0:00:44
   ---------------- ----------------------- 11.3/27.6 MB 382.5 kB/s eta 0:00:43
   ---------------- ----------------------- 11.3/27.6 MB 382.5 kB/s eta 0:00:43
   ---------------- ----------------------- 11.5/27.6 MB 386.2 kB/s eta 0:00:42
   ----------------- ---------------------- 11.8/27.6 MB 390.2 kB/s eta 0:00:41
   ----------------- ---------------------- 11.8/27.6 MB 390.2 kB/s eta 0:00:41
   ----------------- ---------------------- 12.1/27.6 MB 394.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.1/27.6 MB 394.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.1/27.6 MB 394.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.1/27.6 MB 394.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ----------------- ---------------------- 12.3/27.6 MB 384.5 kB/s eta 0:00:40
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.6/27.6 MB 314.7 kB/s eta 0:00:48
   ------------------ --------------------- 12.8/27.6 MB 248.8 kB/s eta 0:01:00
   ------------------ --------------------- 12.8/27.6 MB 248.8 kB/s eta 0:01:00
   ------------------ --------------------- 12.8/27.6 MB 248.8 kB/s eta 0:01:00
   ------------------ --------------------- 12.8/27.6 MB 248.8 kB/s eta 0:01:00
   ------------------ --------------------- 12.8/27.6 MB 248.8 kB/s eta 0:01:00
   ------------------ --------------------- 12.8/27.6 MB 248.8 kB/s eta 0:01:00
   ------------------ --------------------- 12.8/27.6 MB 248.8 kB/s eta 0:01:00
   ------------------ --------------------- 12.8/27.6 MB 248.8 kB/s eta 0:01:00
   ------------------ --------------------- 13.1/27.6 MB 260.7 kB/s eta 0:00:56
   ------------------ --------------------- 13.1/27.6 MB 260.7 kB/s eta 0:00:56
   ------------------ --------------------- 13.1/27.6 MB 260.7 kB/s eta 0:00:56
   ------------------ --------------------- 13.1/27.6 MB 260.7 kB/s eta 0:00:56
   ------------------- -------------------- 13.4/27.6 MB 262.3 kB/s eta 0:00:55
   ------------------- -------------------- 13.4/27.6 MB 262.3 kB/s eta 0:00:55
   ------------------- -------------------- 13.4/27.6 MB 262.3 kB/s eta 0:00:55
   ------------------- -------------------- 13.6/27.6 MB 265.6 kB/s eta 0:00:53
   ------------------- -------------------- 13.6/27.6 MB 265.6 kB/s eta 0:00:53
   ------------------- -------------------- 13.6/27.6 MB 265.6 kB/s eta 0:00:53
   -------------------- ------------------- 13.9/27.6 MB 289.9 kB/s eta 0:00:48
   -------------------- ------------------- 13.9/27.6 MB 289.9 kB/s eta 0:00:48
   -------------------- ------------------- 14.2/27.6 MB 294.3 kB/s eta 0:00:46
   -------------------- ------------------- 14.2/27.6 MB 294.3 kB/s eta 0:00:46
   -------------------- ------------------- 14.4/27.6 MB 299.1 kB/s eta 0:00:45
   -------------------- ------------------- 14.4/27.6 MB 299.1 kB/s eta 0:00:45
   --------------------- ------------------ 14.7/27.6 MB 304.0 kB/s eta 0:00:43
   --------------------- ------------------ 14.7/27.6 MB 304.0 kB/s eta 0:00:43
   --------------------- ------------------ 14.9/27.6 MB 309.3 kB/s eta 0:00:41
   --------------------- ------------------ 14.9/27.6 MB 309.3 kB/s eta 0:00:41
   ---------------------- ----------------- 15.2/27.6 MB 314.7 kB/s eta 0:00:40
   ---------------------- ----------------- 15.5/27.6 MB 320.3 kB/s eta 0:00:38
   ---------------------- ----------------- 15.5/27.6 MB 320.3 kB/s eta 0:00:38
   ---------------------- ----------------- 15.7/27.6 MB 326.0 kB/s eta 0:00:37
   ----------------------- ---------------- 16.0/27.6 MB 365.8 kB/s eta 0:00:32
   ----------------------- ---------------- 16.0/27.6 MB 365.8 kB/s eta 0:00:32
   ----------------------- ---------------- 16.3/27.6 MB 370.9 kB/s eta 0:00:31
   ----------------------- ---------------- 16.3/27.6 MB 370.9 kB/s eta 0:00:31
   ----------------------- ---------------- 16.5/27.6 MB 375.8 kB/s eta 0:00:30
   ----------------------- ---------------- 16.5/27.6 MB 375.8 kB/s eta 0:00:30
   ------------------------ --------------- 16.8/27.6 MB 380.2 kB/s eta 0:00:29
   ------------------------ --------------- 17.0/27.6 MB 384.7 kB/s eta 0:00:28
   ------------------------ --------------- 17.0/27.6 MB 384.7 kB/s eta 0:00:28
   ------------------------- -------------- 17.3/27.6 MB 388.7 kB/s eta 0:00:27
   ------------------------- -------------- 17.3/27.6 MB 388.7 kB/s eta 0:00:27
   ------------------------- -------------- 17.6/27.6 MB 393.1 kB/s eta 0:00:26
   ------------------------- -------------- 17.6/27.6 MB 393.1 kB/s eta 0:00:26
   ------------------------- -------------- 17.8/27.6 MB 397.5 kB/s eta 0:00:25
   -------------------------- ------------- 18.1/27.6 MB 402.0 kB/s eta 0:00:24
   -------------------------- ------------- 18.1/27.6 MB 402.0 kB/s eta 0:00:24
   -------------------------- ------------- 18.4/27.6 MB 406.4 kB/s eta 0:00:23
   -------------------------- ------------- 18.6/27.6 MB 411.1 kB/s eta 0:00:22
   -------------------------- ------------- 18.6/27.6 MB 411.1 kB/s eta 0:00:22

In [5]:
pip install cufflinks

Requirement already satisfied: cufflinks in c:\users\hp\anaconda3\lib\site-packages (0.17.3)
Requirement already satisfied: numpy>=1.9.2 in c:\users\hp\anaconda3\lib\site-packages (from cufflinks) (1.26.4)
Requirement already satisfied: pandas>=0.19.2 in c:\users\hp\anaconda3\lib\site-packages (from cufflinks) (2.2.2)
Requirement already satisfied: plotly>=4.1.1 in c:\users\hp\anaconda3\lib\site-packages (from cufflinks) (5.22.0)
Requirement already satisfied: six>=1.9.0 in c:\users\hp\anaconda3\lib\site-packages (from cufflinks) (1.16.0)
Requirement already satisfied: colorlover>=0.2.1 in c:\users\hp\anaconda3\lib\site-packages (from cufflinks) (0.3.0)
Requirement already satisfied: setuptools>=34.4.1 in c:\users\hp\anaconda3\lib\site-packages (from cufflinks) (69.5.1)
Requirement already satisfied: ipython>=5.3.0 in c:\users\hp\anaconda3\lib\site-packages (from cufflinks) (8.25.0)
Requirement already satisfied: ipywidgets>=7.0.0 in c:\users\hp\anaconda3\lib\site-packages (from cufflinks) (7.8.1)
Requirement already satisfied: decorator in c:\users\hp\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\hp\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\hp\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\hp\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\hp\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (2.15.1)
Requirement already satisfied: stack-data in c:\users\hp\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\hp\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (5.14.3)
Requirement already satisfied: colorama in c:\users\hp\anaconda3\lib\site-packages (from ipython>=5.3.0->cufflinks) (0.4.6)
Requirement already satisfied: comm>=0.1.3 in c:\users\hp\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\users\hp\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.6 in c:\users\hp\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (3.6.6)
Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in c:\users\hp\anaconda3\lib\site-packages (from ipywidgets>=7.0.0->cufflinks) (1.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=0.19.2->cufflinks) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=0.19.2->cufflinks) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas>=0.19.2->cufflinks) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\hp\anaconda3\lib\site-packages (from plotly>=4.1.1->cufflinks) (8.2.2)
Requirement already satisfied: packaging in c:\users\hp\anaconda3\lib\site-packages (from plotly>=4.1.1->cufflinks) (23.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\hp\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->cufflinks) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\hp\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->cufflinks) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in c:\users\hp\anaconda3\lib\site-packages (from widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (7.0.8)
Requirement already satisfied: executing in c:\users\hp\anaconda3\lib\site-packages (from stack-data->ipython>=5.3.0->cufflinks) (0.8.3)
Requirement already satisfied: asttokens in c:\users\hp\anaconda3\lib\site-packages (from stack-data->ipython>=5.3.0->cufflinks) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\hp\anaconda3\lib\site-packages (from stack-data->ipython>=5.3.0->cufflinks) (0.2.2)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\hp\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.14.1)
Requirement already satisfied: jupyterlab-server<3,>=2.22.1 in c:\users\hp\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.25.1)
Requirement already satisfied: jupyterlab<4.1,>=4.0.2 in c:\users\hp\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (4.0.11)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\hp\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.2.3)
Requirement already satisfied: tornado>=6.2.0 in c:\users\hp\anaconda3\lib\site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (6.4.1)
Requirement already satisfied: anyio>=3.1.0 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (4.2.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (21.3.0)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (3.1.4)
Requirement already satisfied: jupyter-client>=7.4.4 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (5.7.2)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.4.4)
Requirement already satisfied: nbconvert>=6.4.4 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (7.10.0)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (5.9.2)
Requirement already satisfied: overrides>=5.0 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (7.4.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.14.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.0.10)
Requirement already satisfied: pyzmq>=24 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (25.1.2)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.17.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\hp\anaconda3\lib\site-packages (from jupyterlab<4.1,>=4.0.2->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.0.4)
Requirement already satisfied: ipykernel in c:\users\hp\anaconda3\lib\site-packages (from jupyterlab<4.1,>=4.0.2->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (6.28.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\hp\anaconda3\lib\site-packages (from jupyterlab<4.1,>=4.0.2->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.2.0)
Requirement already satisfied: babel>=2.10 in c:\users\hp\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.11.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.9.6)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\hp\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (4.19.2)
Requirement already satisfied: requests>=2.31 in c:\users\hp\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.32.2)
Requirement already satisfied: idna>=2.8 in c:\users\hp\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\users\hp\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\hp\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (21.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.10.6)
Requirement already satisfied: platformdirs>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (305.1)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (6.0.1)
Requirement already satisfied: rfc3339-validator in c:\users\hp\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\hp\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.1.1)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in c:\users\hp\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (4.1.0)
Requirement already satisfied: defusedxml in c:\users\hp\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\hp\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.1.2)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\hp\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.0.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\hp\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.8.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\hp\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.5.0)
Requirement already satisfied: tinycss2 in c:\users\hp\anaconda3\lib\site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.2.1)
Requirement already satisfied: fastjsonschema in c:\users\hp\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.16.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.0.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.22.1->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2024.6.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\hp\anaconda3\lib\site-packages (from ipykernel->jupyterlab<4.1,>=4.0.2->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.6.7)
Requirement already satisfied: nest-asyncio in c:\users\hp\anaconda3\lib\site-packages (from ipykernel->jupyterlab<4.1,>=4.0.2->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.6.0)
Requirement already satisfied: psutil in c:\users\hp\anaconda3\lib\site-packages (from ipykernel->jupyterlab<4.1,>=4.0.2->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (5.9.0)
Requirement already satisfied: webencodings in c:\users\hp\anaconda3\lib\site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (0.5.1)
Requirement already satisfied: fqdn in c:\users\hp\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.5.1)
Requirement already satisfied: isoduration in c:\users\hp\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.1)
Requirement already satisfied: uri-template in c:\users\hp\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.3.0)
Requirement already satisfied: webcolors>=1.11 in c:\users\hp\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (25.10.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\hp\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.16.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.5)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (2.21)
Requirement already satisfied: arrow>=0.15.0 in c:\users\hp\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.6->ipywidgets>=7.0.0->cufflinks) (1.2.3)
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install jupyter_contrib_nbextensions

Collecting jupyter_contrib_nbextensions
  Using cached jupyter_contrib_nbextensions-0.7.0-py2.py3-none-any.whl
Collecting ipython-genutils (from jupyter_contrib_nbextensions)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Collecting jupyter-contrib-core>=0.3.3 (from jupyter_contrib_nbextensions)
  Using cached jupyter_contrib_core-0.4.2-py2.py3-none-any.whl
Requirement already satisfied: jupyter-core in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jupyter_contrib_nbextensions) (5.9.1)
Collecting jupyter-highlight-selected-word>=0.1.1 (from jupyter_contrib_nbextensions)
  Using cached jupyter_highlight_selected_word-0.2.0-py2.py3-none-any.whl.metadata (730 bytes)
Collecting jupyter-nbextensions-configurator>=0.4.0 (from jupyter_contrib_nbextensions)
  Using cached jupyter_nbextensions_configurator-0.6.4-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting nbconvert>=6.0 (from jupyter_contrib_nbextensions)
  Downloading nbconvert-7.17.0-py3-none-any.whl.metadata (8.4 kB)
Collecting notebook>=6.0 (from jupyter_contrib_nbextensions)
  Downloading notebook-7.5.5-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: tornado in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jupyter_contrib_nbextensions) (6.5.5)
Requirement already satisfied: traitlets>=4.1 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jupyter_contrib_nbextensions) (5.14.3)
Collecting lxml (from jupyter_contrib_nbextensions)
  Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl.metadata (3.7 kB)
Collecting setuptools (from jupyter-contrib-core>=0.3.3->jupyter_contrib_nbextensions)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting jupyter-server (from jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading jupyter_server-2.17.0-py3-none-any.whl.metadata (8.5 kB)
Collecting pyyaml (from jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Collecting beautifulsoup4 (from nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting defusedxml (from nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jinja2>=3.0 (from nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyterlab-pygments (from nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting markupsafe>=2.0 (from nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading markupsafe-3.0.3-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading mistune-3.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading nbclient-0.10.4-py3-none-any.whl.metadata (8.3 kB)
Collecting nbformat>=5.7 (from nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from nbconvert>=6.0->jupyter_contrib_nbextensions) (26.0)
Collecting pandocfilters>=1.4.1 (from nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: pygments>=2.4.1 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from nbconvert>=6.0->jupyter_contrib_nbextensions) (2.19.2)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: platformdirs>=2.5 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jupyter-core->jupyter_contrib_nbextensions) (4.9.4)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from nbclient>=0.5.0->nbconvert>=6.0->jupyter_contrib_nbextensions) (8.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=6.0->jupyter_contrib_nbextensions) (2.9.0.post0)
Requirement already satisfied: pyzmq>=25.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=6.0->jupyter_contrib_nbextensions) (27.1.0)
Collecting fastjsonschema>=2.15 (from nbformat>=5.7->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting jsonschema>=2.6 (from nbformat>=5.7->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading rpds_py-0.30.0-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting jupyterlab<4.6,>=4.5.6 (from notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading jupyterlab-4.5.6-py3-none-any.whl.metadata (16 kB)
Collecting notebook-shim<0.3,>=0.2 (from notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting anyio>=3.1.0 (from jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Collecting argon2-cffi>=21.1 (from jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading jupyter_events-0.12.0-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting prometheus-client>=0.9 (from jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading prometheus_client-0.24.1-py3-none-any.whl.metadata (2.1 kB)
Collecting pywinpty>=2.0.1 (from jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading pywinpty-3.0.3-cp312-cp312-win_amd64.whl.metadata (5.9 kB)
Collecting send2trash>=1.8.2 (from jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting async-lru>=1.0.0 (from jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Collecting httpx<1,>=0.25.0 (from jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (7.2.0)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading jupyter_lsp-2.3.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: certifi in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (2026.2.25)
Collecting httpcore==1.* (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (3.11)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->notebook>=6.0->jupyter_contrib_nbextensions)
  Downloading json5-0.13.0-py3-none-any.whl.metadata (36 kB)
Requirement already satisfied: requests>=2.31 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->notebook>=6.0->jupyter_contrib_nbextensions) (2.32.5)
Collecting typing_extensions>=4.5 (from anyio>=3.1.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl.metadata (7.5 kB)
Requirement already satisfied: comm>=0.1.1 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (9.11.0)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (1.6.0)
Requirement already satisfied: psutil>=5.7 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (7.2.2)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (3.0.52)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (0.6.3)
Requirement already satisfied: wcwidth in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (0.8.6)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading python_json_logger-4.0.0-py3-none-any.whl.metadata (4.0 kB)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading jsonpointer-3.1.0-py3-none-any.whl.metadata (2.4 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Using cached webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: six>=1.5 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=6.0->jupyter_contrib_nbextensions) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook>=6.0->jupyter_contrib_nbextensions) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->notebook>=6.0->jupyter_contrib_nbextensions) (2.6.3)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: executing>=1.2.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (3.0.1)
Requirement already satisfied: pure-eval in c:\Users\HP\Desktop\@data_science_projects_portfolio\alx_python_track\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab<4.6,>=4.5.6->notebook>=6.0->jupyter_contrib_nbextensions) (0.2.3)
Collecting cffi>=1.0.1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading cffi-2.0.0-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert>=6.0->jupyter_contrib_nbextensions)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server->jupyter-nbextensions-configurator>=0.4.0->jupyter_contrib_nbextensions)
  Downloading arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)

In [23]:
!jupyter nbextension enable --py widgetsnbextension

usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: console contrib dejavu events execute kernel kernelspec
lab labextension labhub migrate nbconvert nbextensions_configurator notebook
qtconsole run script server troubleshoot trust

Jupyter command `jupyter-nbextension` not found.

In [9]:
pip install jupyter-nbextension

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement jupyter-nbextension (from versions: none)
ERROR: No matching distribution found for jupyter-nbextension

In [9]:
# 3. Import the required packages

import numpy as np
import pandas as pd
import scipy


# Instantiate the Plotly charting library
import chart_studio.plotly as py
import plotly.graph_objs as go
import plotly.express as px
# We use plotly.offline as this allows us to create interactive 
# visualisations without the use of an internet connection, 
# making our notebook more distributable to others. 
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

# The Cufflinks library allows us to directly bind 
# Pandas DataFrames to Plotly charts. 
import cufflinks as cf
# Once again, we use the Cufflinks library in offline mode. 
cf.go_offline(connected=True)
cf.set_config_file(colorscale='plotly', world_readable=True)

# Extra options. We use these to make our interactive 
# visualisations more aesthetically appealing. 
from IPython.core.display import HTML
pd.options.display.max_rows = 30
pd.options.display.max_columns = 25

# Show all code cells outputs.
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [10]:
df = pd.read_parquet('https://github.com/WillKoehrsen/Data-Analysis/blob/master/medium/data/medium_data_2019_01_26?raw=true')
df.head()

,claps,days_since_publication,fans,link,num_responses,publication,published_date,read_ratio,read_time,reads,started_date,tags,text,title,title_word_count,type,views,word_count,claps_per_word,editing_days,<tag>Education,<tag>Data Science,<tag>Towards Data Science,<tag>Machine Learning,<tag>Python
129,2,597.301123,2,https://medium.com/p/screw-the-environment-but...,0,None,2017-06-10 14:25:00,42.17,7,70,2017-06-10 14:24:00,"[Climate Change, Economics]","Screw the Environment, but Consider Your Walle...","Screw the Environment, but Consider Your Wallet",8,published,166,1859,0.001076,0,0,0,0,0,0
125,18,589.983168,3,https://medium.com/p/the-vanquishing-of-war-pl...,0,None,2017-06-17 22:02:00,30.34,14,54,2017-06-17 22:02:00,"[Climate Change, Humanity, Optimism, History]","The Vanquishing of War, Plague and Famine Part...","The Vanquishing of War, Plague and Famine",8,published,178,3891,0.004626,0,0,0,0,0,0
132,51,577.363292,20,https://medium.com/p/capstone-project-mercedes...,0,None,2017-06-30 12:55:00,20.02,42,222,2017-06-30 12:00:00,"[Machine Learning, Python, Udacity, Kaggle]",Capstone Project: Mercedes-Benz Greener Manufa...,Capstone Project: Mercedes-Benz Greener Manufa...,7,published,1109,12025,0.004241,0,0,0,0,1,1
126,0,576.520688,0,https://medium.com/p/home-of-the-scared-5af0fe...,0,None,2017-07-01 09:08:00,35.85,9,19,2017-06-30 18:21:00,"[Politics, Books, News, Media Criticism]",Home of the Scared A review of A Culture of Fe...,Home of the Scared,4,published,53,2533,0.000000,0,0,0,0,0,0
121,0,572.533035,0,https://medium.com/p/the-triumph-of-peace-f485...,0,None,2017-07-05 08:51:00,8.47,14,5,2017-07-03 20:18:00,"[Books, Psychology, History, Humanism]",The Triumph of Peace A review of The Better An...,The Triumph of Peace,4,published,59,3892,0.000000,1,0,0,0,0,0

In [11]:
df.describe()

,claps,days_since_publication,fans,num_responses,published_date,read_ratio,read_time,reads,started_date,title_word_count,views,word_count,claps_per_word,editing_days,<tag>Education,<tag>Data Science,<tag>Towards Data Science,<tag>Machine Learning,<tag>Python
count,133.000000,133.000000,133.000000,133.000000,133,133.000000,133.000000,133.000000,133,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000,133.000000
mean,1815.263158,248.407273,352.052632,7.045113,2018-05-25 11:51:41.954000,29.074662,12.917293,6336.300752,2018-05-04 16:41:25.714000,7.127820,23404.030075,3029.120301,0.957638,20.330827,0.729323,0.609023,0.436090,0.383459,0.315789
min,0.000000,1.218629,0.000000,0.000000,2017-06-10 14:25:00,8.110000,1.000000,1.000000,2017-06-10 14:24:00,2.000000,3.000000,163.000000,0.000000,-13.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,121.000000,74.543822,23.000000,0.000000,2018-01-17 19:42:00,20.020000,8.000000,363.000000,2018-01-10 08:20:00,5.000000,1375.000000,1653.000000,0.052115,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,815.000000,245.416130,136.000000,4.000000,2018-05-28 11:39:00,27.060000,10.000000,2049.000000,2018-04-28 13:02:00,7.000000,7608.000000,2456.000000,0.421525,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,2700.000000,376.080598,528.000000,12.000000,2018-11-15 08:35:00,34.910000,14.000000,7815.000000,2018-10-14 08:24:00,8.000000,30141.000000,3553.000000,1.099366,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,13600.000000,597.301123,2588.000000,59.000000,2019-01-27 16:23:00,74.370000,54.000000,41978.000000,2019-01-27 06:26:00,16.000000,173714.000000,15063.000000,17.891817,349.000000,1.000000,1.000000,1.000000,1.000000,1.000000
std,2449.074661,179.370879,479.060117,9.056108,NaN,12.417670,9.510795,9007.284726,NaN,3.158475,33995.636496,2393.414456,1.846756,74.111579,0.445989,0.489814,0.497774,0.488067,0.466587

# Examples

In [12]:
from ipywidgets import interact, interact_manual, widgets

In [13]:
@interact
def show_articles_more_than(column='claps', x=5000):
    display(HTML(f'<h4>Showing articles with more than {x} {column}<h4>'))
    display(df.loc[df[column] > x, ['title', 'claps', 'published_date', 'read_time', 'tags', 'views', 'reads']])

interactive(children=(Text(value='claps', description='column'), IntSlider(value=5000, description='x', max=15…

In [14]:
@interact
def show_titles_more_than(x=(10, 50000, 10),
                          column=['read_time', 'views', 'reads']):
    display(HTML(f'<h4>Showing articles with more than {x} {column}<h4>'))
    display(df.loc[df[column] > x, ['title', 'published_date', 'read_time', 'tags', 'views', 'reads']])

interactive(children=(IntSlider(value=25000, description='x', max=50000, min=10, step=10), Dropdown(descriptio…

In [15]:
@interact
def correlations(column1=list(df.select_dtypes('number').columns),
                 column2=list(df.select_dtypes('number').columns)):
    print(f"Correlation: {df[column1].corr(df[column2])}")

interactive(children=(Dropdown(description='column1', options=('claps', 'days_since_publication', 'fans', 'num…

In [16]:
@interact
def scatter_plot(x=list(df.select_dtypes('number').columns),
                 y=list(df.select_dtypes('number').columns)[1:]):
    if x == y:
        print(f"Please select separate variables for X and Y")
    else:
        df.iplot(kind='scatter', x=x, y=y, mode='markers',
                 xTitle=x.title(), yTitle=y.title(), title=f'{y.title()} vs {x.title()}')
        ## If you are using Google Colab, comment out the above line of code and uncomment the lines below
        #fig = px.scatter(df, x=x, y=y, title=f'{y.title()} vs {x.title()}')
        #fig.show(renderer="colab")

interactive(children=(Dropdown(description='x', options=('claps', 'days_since_publication', 'fans', 'num_respo…

In [3]:
cscales = ['Greys', 'YlGnBu', 'Greens', 'YlOrRd', 'Bluered', 'RdBu',
            'Reds', 'Blues', 'Picnic', 'Rainbow', 'Portland', 'Jet',
            'Hot', 'Blackbody', 'Earth', 'Electric', 'Viridis', 'Cividis']

# We use the Figure Factory module of Plotly, which
# defines many unique and powerful plots to be used
# in Python. 
# For more info, see: https://plot.ly/python/figure-factory-subplots/
import plotly.figure_factory as ff

corrs = df.corr(numeric_only=True)

@interact
def plot_corrs(colorscale=cscales):
    figure = ff.create_annotated_heatmap(z = corrs.round(2).values,
                                     x =list(corrs.columns),
                                     y=list(corrs.index),
                                     colorscale=colorscale,
                                     annotation_text=corrs.round(2).values)
    iplot(figure)
    ## If you are using Google Colab, comment out the above line of code and uncomment the line below
    #figure.show(renderer="colab")

ModuleNotFoundError: No module named 'plotly'

In [18]:
@interact_manual
def scatter_plot(x=list(df.select_dtypes('number').columns),
                 y=list(df.select_dtypes('number').columns)[1:],
                 theme=list(cf.themes.THEMES.keys()),
                 colorscale=list(cf.colors._scales_names.keys())):

    if x == y:
        print(f"Please select separate variables for X and Y")
    else:
        df.iplot(kind='scatter', x=x, y=y, mode='markers',
                 xTitle=x.title(), yTitle=y.title(),
                 text='title',
                 title=f'{y.title()} vs {x.title()}',
                theme=theme, colorscale=colorscale)
        ## If you are using Google Colab, comment out the above line of code and uncomment the line below
        #fig = px.scatter(df, x=x, y=y, title=f'{y.title()} vs {x.title()}')
        #fig.show(renderer="colab")

interactive(children=(Dropdown(description='x', options=('claps', 'days_since_publication', 'fans', 'num_respo…

In [19]:
df.set_index('published_date', inplace=True)

In [20]:
def print_articles_published(start_date, end_date):
    start_date = pd.Timestamp(start_date)
    end_date = pd.Timestamp(end_date)
    stat_df = df.loc[(df.index >= start_date) & (df.index <= end_date)].copy()
    total_words = stat_df['word_count'].sum()
    total_read_time = stat_df['read_time'].sum()
    num_articles = len(stat_df)
    print(f'According to our dataset, published by Medium.com, there are {num_articles} articles between {start_date.date()} and {end_date.date()}.')
    print(f'These articles totalled {total_words:,} words and {total_read_time/60:.2f} hours to read.')

_ = interact(print_articles_published,
             start_date=widgets.DatePicker(value=pd.to_datetime('2018-01-01')),
             end_date=widgets.DatePicker(value=pd.to_datetime('2019-01-01')))

interactive(children=(DatePicker(value=Timestamp('2018-01-01 00:00:00'), description='start_date'), DatePicker…

In [2]:
def plot_up_to(column, date):
    date = pd.Timestamp(date)
    plot_df = df.loc[df.index <= date].copy()
    plot_df[column].cumsum().iplot(mode='markers+lines',
                                   xTitle='published date',
                                   yTitle=column,
                                  title=f'Cumulative {column.title()} Until {date.date()}')

_ = interact(plot_up_to, column=widgets.Dropdown(options=list(df.select_dtypes('number').columns)),
             date = widgets.DatePicker(value=pd.to_datetime('2019-01-01')))

NameError: name 'interact' is not defined